require("config.options")
require("config.pack")
require("config.treesitter")
require("config.snacks")
require("config.keymaps")
require("config.diagnostics")
require("config.autocmds")
require("config.lsp")
