local map = function(mode, lhs, rhs, desc)
  -- See `:h vim.keymap.set()`
  vim.keymap.set(mode, lhs, rhs, { desc = desc })
end

local nmap = function(lhs, rhs, desc) map("n", lhs, rhs, desc) end

nmap("<leader><space>", function() Snacks.picker.smart() end, "Smart Find Files")
nmap("<leader>,", function() Snacks.picker.buffers() end, "Buffers")
nmap("<leader>/", function() Snacks.picker.grep() end, "Grep")
nmap("<leader>:", function() Snacks.picker.command_history() end, "Command History")
nmap("<leader>n", function() Snacks.picker.notifications() end, "Notification History")
nmap("<leader>e", function() Snacks.explorer() end, "File Explorer")
map(
  { "n", "x" },
  "<leader>cf",
  function() require("conform").format({ async = true, lsp_format = "fallback" }) end,
  "Format Buffer/Selection"
)
nmap("<leader>.", function() Snacks.scratch() end, "Toggle Scratch")
nmap("<leader>S", function() Snacks.scratch.select() end, "Select Scratch")
nmap("<leader>fb", function() Snacks.picker.buffers() end, "Buffers")
nmap("<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, "Find Config File")
nmap("<leader>ff", function() Snacks.picker.files() end, "Find Files")
nmap("<leader>fg", function() Snacks.picker.git_files() end, "Find Git Files")
nmap("<leader>fp", function() Snacks.picker.projects() end, "Projects")
nmap("<leader>fr", function() Snacks.picker.recent() end, "Recent")
nmap("<leader>gb", function() Snacks.picker.git_branches() end, "Git Branches")
nmap("<leader>gl", function() Snacks.picker.git_log() end, "Git Log")
nmap("<leader>gL", function() Snacks.picker.git_log_line() end, "Git Log Line")
nmap("<leader>gs", function() Snacks.picker.git_status() end, "Git Status")
nmap("<leader>gS", function() Snacks.picker.git_stash() end, "Git Stash")
nmap("<leader>gd", function() Snacks.picker.git_diff() end, "Git Diff (Hunks)")
nmap("<leader>gf", function() Snacks.picker.git_log_file() end, "Git Log File")
nmap("<leader>gi", function() Snacks.picker.gh_issue() end, "GitHub Issues (open)")
nmap("<leader>gI", function() Snacks.picker.gh_issue({ state = "all" }) end, "GitHub Issues (all)")
nmap("<leader>gp", function() Snacks.picker.gh_pr() end, "GitHub Pull Requests (open)")
nmap("<leader>gP", function() Snacks.picker.gh_pr({ state = "all" }) end, "GitHub Pull Requests (all)")
nmap("<leader>sb", function() Snacks.picker.lines() end, "Buffer Lines")
nmap("<leader>sB", function() Snacks.picker.grep_buffers() end, "Grep Open Buffers")
nmap("<leader>sg", function() Snacks.picker.grep() end, "Grep")
map({ "n", "x" }, "<leader>sw", function() Snacks.picker.grep_word() end, "Visual selection or word")
nmap('<leader>s"', function() Snacks.picker.registers() end, "Registers")
nmap("<leader>s/", function() Snacks.picker.search_history() end, "Search History")
nmap("<leader>sa", function() Snacks.picker.autocmds() end, "Autocmds")
nmap("<leader>sc", function() Snacks.picker.command_history() end, "Command History")
nmap("<leader>sC", function() Snacks.picker.commands() end, "Commands")
nmap("<leader>sd", function() Snacks.picker.diagnostics() end, "Diagnostics")
nmap("<leader>sD", function() Snacks.picker.diagnostics_buffer() end, "Buffer Diagnostics")
nmap("<leader>sh", function() Snacks.picker.help() end, "Help Pages")
nmap("<leader>sH", function() Snacks.picker.highlights() end, "Highlights")
nmap("<leader>si", function() Snacks.picker.icons() end, "Icons")
nmap("<leader>sj", function() Snacks.picker.jumps() end, "Jumps")
nmap("<leader>sk", function() Snacks.picker.keymaps() end, "Keymaps")
nmap("<leader>sl", function() Snacks.picker.loclist() end, "Location List")
nmap("<leader>sm", function() Snacks.picker.marks() end, "Marks")
nmap("<leader>sM", function() Snacks.picker.man() end, "Man Pages")
nmap("<leader>sp", function() Snacks.picker.lazy() end, "Search for Plugin Spec")
nmap("<leader>sq", function() Snacks.picker.qflist() end, "Quickfix List")
nmap("<leader>sR", function() Snacks.picker.resume() end, "Resume")
nmap("<leader>su", function() Snacks.picker.undo() end, "Undo History")
nmap("<leader>uC", function() Snacks.picker.colorschemes() end, "Colorschemes")
nmap("gd", function() Snacks.picker.lsp_definitions() end, "Goto Definition")
nmap("gD", function() Snacks.picker.lsp_declarations() end, "Goto Declaration")
nmap("gr", function() Snacks.picker.lsp_references() end, "References")
nmap("gI", function() Snacks.picker.lsp_implementations() end, "Goto Implementation")
nmap("gy", function() Snacks.picker.lsp_type_definitions() end, "Goto T[y]pe Definition")
nmap("gai", function() Snacks.picker.lsp_incoming_calls() end, "C[a]lls Incoming")
nmap("gao", function() Snacks.picker.lsp_outgoing_calls() end, "C[a]lls Outgoing")
nmap("<leader>ss", function() Snacks.picker.lsp_symbols() end, "LSP Symbols")
nmap("<leader>sS", function() Snacks.picker.lsp_workspace_symbols() end, "LSP Workspace Symbols")
