vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true
vim.o.scrolloff = 4
vim.o.cursorline = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.signcolumn = "yes"
vim.o.list = true
vim.opt.listchars = {
	tab = "» ",
	trail = "·",
	nbsp = "␣",
}
vim.o.undofile = true
vim.o.wildmenu = true
vim.o.wildmode = "longest:full,full"
vim.o.showcmd = true
vim.o.number = true
vim.o.autocomplete = true
vim.o.pumborder = "rounded"
vim.o.pummaxwidth = 40
vim.opt.completeopt = { "menu", "menuone", "noselect" }
